name: Deploy to Render

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    # Only run this job if the previous workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Triggering Render deployment..."
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_PROJECT_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
          
          echo "Deployment webhook triggered successfully!"

      - name: Verify deployment trigger
        run: |
          echo "Deployment has been triggered on Render.com"
          echo "Check your Render dashboard for deployment status"
